package datos;
// Generated 28-may-2023 20:09:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int empid;
     private String empcedularuc;
     private String empnombre;
     private String emptelefono;
     private String empdireccion;
     private String empmail;
     private String emplogo;
     private String facebook;
     private String twitter;
     private String instagram;
     private String tiktok;
     private Date fechacrea;
     private Date fechamodi;
     private String usuariocrea;
     private String usuariomodi;

    public Empresa() {
    }

	
    public Empresa(int empid, String empcedularuc, String empnombre, String emptelefono, String empdireccion, String empmail, Date fechacrea, Date fechamodi, String usuariocrea, String usuariomodi) {
        this.empid = empid;
        this.empcedularuc = empcedularuc;
        this.empnombre = empnombre;
        this.emptelefono = emptelefono;
        this.empdireccion = empdireccion;
        this.empmail = empmail;
        this.fechacrea = fechacrea;
        this.fechamodi = fechamodi;
        this.usuariocrea = usuariocrea;
        this.usuariomodi = usuariomodi;
    }
    public Empresa(int empid, String empcedularuc, String empnombre, String emptelefono, String empdireccion, String empmail, String emplogo, String facebook, String twitter, String instagram, String tiktok, Date fechacrea, Date fechamodi, String usuariocrea, String usuariomodi) {
       this.empid = empid;
       this.empcedularuc = empcedularuc;
       this.empnombre = empnombre;
       this.emptelefono = emptelefono;
       this.empdireccion = empdireccion;
       this.empmail = empmail;
       this.emplogo = emplogo;
       this.facebook = facebook;
       this.twitter = twitter;
       this.instagram = instagram;
       this.tiktok = tiktok;
       this.fechacrea = fechacrea;
       this.fechamodi = fechamodi;
       this.usuariocrea = usuariocrea;
       this.usuariomodi = usuariomodi;
    }
   
    public int getEmpid() {
        return this.empid;
    }
    
    public void setEmpid(int empid) {
        this.empid = empid;
    }
    public String getEmpcedularuc() {
        return this.empcedularuc;
    }
    
    public void setEmpcedularuc(String empcedularuc) {
        this.empcedularuc = empcedularuc;
    }
    public String getEmpnombre() {
        return this.empnombre;
    }
    
    public void setEmpnombre(String empnombre) {
        this.empnombre = empnombre;
    }
    public String getEmptelefono() {
        return this.emptelefono;
    }
    
    public void setEmptelefono(String emptelefono) {
        this.emptelefono = emptelefono;
    }
    public String getEmpdireccion() {
        return this.empdireccion;
    }
    
    public void setEmpdireccion(String empdireccion) {
        this.empdireccion = empdireccion;
    }
    public String getEmpmail() {
        return this.empmail;
    }
    
    public void setEmpmail(String empmail) {
        this.empmail = empmail;
    }
    public String getEmplogo() {
        return this.emplogo;
    }
    
    public void setEmplogo(String emplogo) {
        this.emplogo = emplogo;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getInstagram() {
        return this.instagram;
    }
    
    public void setInstagram(String instagram) {
        this.instagram = instagram;
    }
    public String getTiktok() {
        return this.tiktok;
    }
    
    public void setTiktok(String tiktok) {
        this.tiktok = tiktok;
    }
    public Date getFechacrea() {
        return this.fechacrea;
    }
    
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }
    public Date getFechamodi() {
        return this.fechamodi;
    }
    
    public void setFechamodi(Date fechamodi) {
        this.fechamodi = fechamodi;
    }
    public String getUsuariocrea() {
        return this.usuariocrea;
    }
    
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea;
    }
    public String getUsuariomodi() {
        return this.usuariomodi;
    }
    
    public void setUsuariomodi(String usuariomodi) {
        this.usuariomodi = usuariomodi;
    }




}


